### ISSUE TITLE
Heatmap data

### ISSUE THREAD

**Issue by humana** [nicgirault/circosJS#43]
Hi,

Firstly... amazing library! Well done. It looks spectacular.

The documentation for Heatmap on the front page says the data should look like this:
Data format:

var data = [
    // each datum should be 
    // layout_block_id, start, end, value 
    ['january', 0, 1, 1368001],
    ['january', 1, 2, 1458583],
    ['january', 2, 3, 1481633],
]

i.e. each datum is an array.  However, when I tried using this nothing would render.

When I changed the data format to use objects as datum:

var data = [
    {
      block_id: 'january',
      start: 1,
      end: 10,
      value: 5
    }
];

Then it renders.  I spent many hours trying to debug why it wasn't working.  This is either a bug (I think it should accept the array datum, Highchart series work this way) or else a regression?

**Comment by nicgirault** [comment]
Thanks @humana for reporting this issue and sorry for the delay to answer. I fixed the documentation.

I chose to remove the array data so that there is no confusion with 2 possible ways to input data. It seems to me easy enough to switch from one to the other so it can be handle outside of circosjs. For example:

```javascript
data.map(datum => ({
  block_id: datum[0],
  start: datum[1],
  end: datum[2],
  value: datum[3]
}))
```

will do the job for heatmap.

Let me know if you have any argument against this choice.

Thanks again for reporting this bug
